settings:
  # 组合键超时时间（毫秒）
  combo-timeout: 600
  # 多次潜行检测超时时间（毫秒） 如果shift无法达到预设值，请调大这个
  multi-sneak-timeout: 600
  # 显示按键次数
  show-sneak-count: true
  sneak-count-actionbar: true
  sneak-count-format: "&e按键次数: &a%count%"
  sneak-count-sound: true
  sneak-count-sound-type: BLOCK_NOTE_BLOCK_PLING
  # 是否异步执行命令
  async-commands: true
  # 是否使用权限系统
  use-permissions: true
  # 清理间隔（秒）
  cleanup-interval: 600

  # 冷却设置
  cooldown:
    enabled: true
    show-actionbar: true
    default: 3.0

  # 效果设置
  effects:
    sound:
      enabled: true
      volume: 1.0
      pitch: 1.0
      type: ENTITY_EXPERIENCE_ORB_PICKUP

    particles:
      enabled: true
      count: 10
      spread: 0.5
      type: VILLAGER_HAPPY

  # 消息设置
  messages:
    chat: true
    actionbar: true

hotkeys:
  shift_f:
    enabled: true # 是否启用
    require-sync: false # 是否需要同步
    commands:
      # [op] 管理员执行
      # [cmd] 控制台指令
      # 什么也不加 玩家执行
      # 指令执行
      - "say 我按下了 Shift+F!"
      - "[cmd]give %player% diamond 1"
    conditions:
      # 条件，可删可加
      cooldown: 5.0 # 冷却
      world: world # 世界
      min-health: 10 # 最低需要血量
      min-level: 5 # 嘴子需要等级
    effects:
      sound: ENTITY_PLAYER_LEVELUP # 播放音效
      particle: FIREWORKS_SPARK # 特效：烟花
      message: "&a你使用了 Shift+F 热键!" # title消息

  shift_left:
    enabled: true
    commands:
      - "skill cast fireball"
    conditions:
      cooldown: 2.0
      gamemode: SURVIVAL
    effects:
      sound: ENTITY_BLAZE_SHOOT
      particle: FLAME
      message: "&c火球术!"

  # 双击 Shift（按2次） （可自定义修改后面的123456789）
  double_sneak_2:
    enabled: true
    commands:
      - "say 我双击了 Shift!"
      - "effect give %player% minecraft:speed 10 1"
    conditions:
      cooldown: 2.0
    effects:
      sound: ENTITY_PLAYER_LEVELUP
      particle: SPELL_INSTANT
      message: "&a已2击shift！"

  shift_q:
    enabled: true
    commands:
      - "effect give %player% minecraft:jump_boost 10 1"
    conditions:
      cooldown: 2.0
    effects:
      sound: ENTITY_PLAYER_LEVELUP
      particle: SPELL_INSTANT
      message: "&a已按shift+q！"

  # 四击 Shift（按4次）
  double_sneak_4:
    enabled: true
    commands:
      - "effect give %player% minecraft:levitation 5 1"
    conditions:
      cooldown: 2.0
    effects:
      sound: ENTITY_FIREWORK_ROCKET_LAUNCH
      particle: FIREWORKS_SPARK
      message: "&a已4击shift！"

# 权限配置
# hotkey.use.* 将允许所有热键
permissions:
  shift_f: "hotkey.premium.shift_f"
  double_sneak_2: "hotkey.use.double_sneak_2"
  double_sneak_3: "hotkey.vip.fly"
  double_sneak_4: "hotkey.vip.elytra"
