# 全局设置
settings:
  # 冷却时间设置
  cooldown:
    enabled: true      # 是否启用冷却系统
    global: 3          # 全局冷却时间(秒)
    per_hotkey: true   # 是否允许每个快捷键单独设置冷却时间

  # 特效设置
  effects:
    # 音效设置
    sound:
      enabled: true    # 是否启用音效
      type: ENTITY_EXPERIENCE_ORB_PICKUP  # 默认音效类型
      volume: 1.0      # 音量(0.0-1.0)
      pitch: 1.0       # 音调(0.5-2.0)
    # 粒子效果设置
    particles:
      enabled: true    # 是否启用粒子效果
      type: VILLAGER_HAPPY  # 默认粒子类型
      count: 10        # 粒子数量
      spread: 0.5      # 粒子扩散范围

  # 消息显示设置
  messages:
    actionbar: true    # 是否在动作栏显示消息
    chat: true         # 是否在聊天栏显示消息

  debug: false         # 调试模式(开发用)

# 条件要求类型说明：
# requirements 支持的条件类型：
#   exp_level: 数值        - 需要达到指定经验等级
#   food_level: 数值       - 需要达到指定饥饿值 (最大20)
#   gamemode: 游戏模式      - 需要处于指定游戏模式 (SURVIVAL/CREATIVE/ADVENTURE/SPECTATOR)
#   permission: 权限名      - 需要拥有指定权限
#   has_item: 物品ID       - 背包中需要有指定物品
#   in_world: 世界名        - 需要在指定世界中
#   time_between: [开始,结束] - 服务器时间需要在指定范围内

# 支持的按键组合说明：
# shift_f      - Shift + F键 (切换副手)
# shift_q      - Shift + Q键 (丢弃物品)
# shift_left   - Shift + 左键点击
# shift_right  - Shift + 右键点击
# double_sneak - 双击Shift键

# 快捷键配置
hotkeys:
  # Shift+F组合键配置示例
  shift_f:
    enabled: true
    commands:
      - "spawn"
      - "[cmd]give %player% diamond 1"
      - "effect give @p speed 30 1"
    conditions: # 条件
      permission: "hotkey.use.shift_f" # 权限
      cooldown: 3 # 冷却时间(秒), 0表示无冷却, 覆盖全局冷却
      requirements:
        exp_level: 5        # 需要5级经验
        food_level: 15      # 需要15点饥饿值
        gamemode: SURVIVAL  # 必须在生存模式
    effects:
      sound: BLOCK_NOTE_BLOCK_PLING
      message: "&a快速回城！"

  # Shift+Q组合键配置示例
  shift_q:
    enabled: true
    commands:
      - "kit tools"
      - "[cmd]give %player% bread 16"
    conditions: # 条件
      permission: "hotkey.use.shift_q" # 权限
      cooldown: 3 # 冷却时间(秒), 0表示无冷却, 覆盖全局冷却
      requirements:
        has_item: DIAMOND   # 背包中需要有钻石
        in_world: "world"   # 必须在主世界中
    effects:
      sound: ENTITY_PLAYER_LEVELUP
      message: "&a领取了新手工具包！"

  # Shift+左键配置示例
  shift_left:
    enabled: true
    commands:
      - "[cmd]tpall %player%"                     # 控制台将所有人传送到玩家
    conditions: # 条件
      permission: "hotkey.use.shift_left" # 权限
      cooldown: 3 # 冷却时间(秒), 0表示无冷却, 覆盖全局冷却
      requirements:
        exp_level: 10                             # 需要10级经验
    effects:
      sound: ENTITY_ENDERMAN_TELEPORT
      particle: PORTAL
      message: "&6召集所有玩家！"

  # Shift+右键配置示例
  shift_right:
    enabled: true
    commands:
      - "sethome"                                 # 设置家
      - "[cmd]title %player% title {\"text\":\"设置家成功\",\"color\":\"green\"}"
    conditions: # 条件
      permission: "hotkey.use.shift_right" # 权限
      in_world: "world"                           # 必须在主世界中
    effects:
      sound: BLOCK_ANVIL_USE
      particle: VILLAGER_HAPPY
      message: "&a设置了一个新的家！"

  # 双击Shift配置示例
  double_sneak:
    enabled: true
    commands:
      - "fly"                                     # 切换飞行模式
      - "[cmd]particle cloud %player% ~ ~1 ~ 1 1 1 0.1 50"
    conditions: # 条件
      permission: "hotkey.use.double_sneak" # 权限
    effects:
      sound: ENTITY_BAT_TAKEOFF
      particle: CLOUD
      message: "&b切换飞行模式！" 